package lk.ijse.CityLibrary.util;

public enum Routes {
    DASHBOARDPAGE,USER,MEMBER,BORROWINGDETAIL,DASHBOARDFORM,
    REGISTER,LOGOUT,ADMINPANEL,SALARY,FOGOTPASSWORD,FINE,
    EXPENDITURE,EMPLOYEE,DONATION,CATEGORY,BOOK,ATTENDANCE
}
